using System.Collections.Generic;

namespace AttackBuddy
{
    public static class Constants
    {
        public static List<string> _ignores = new List<string>
        {
                    "Sprysi D'Lere",
<<<<<<< HEAD
=======
                    "Notum Bomb",
>>>>>>> aab7ee3ccaa03c6ad6b10dee74da529f4148bb84
                    "Notum Erruption",
                    "Alien Fuel Tower",
                    "Kyr'Ozch Guardian",
                    "Engorged Sacrificial Husks",
                    "Honor Guard - Ilari'Uri",
                    "Unicorn Recon Agent Chittick",
                    "Representative of IPS",
                    "Transportation Officer Darren Plush",
                    "Unicorn Recruiter",
                    "Unicorn Field Engineer",
                    "Buckethead Technodealer",
                    "Unicorn Commander Labbe",
                    "Professor Raji Masoud",
                    "Slimy Alien Plant",
                    "Awakened Xan",
                    "Calan-Cur",
                    "Spirit of Judgement",
                    "Wandering Spirit",
                    "Altar of Torture",
                    "Altar of Purification",
                    "Unicorn Coordinator Magnum Blaine",
                    "Xan Spirit",
                    "Watchful Spirit",
                    "Amesha Vizaresh",
                    "Guardian Spirit of Purification",
                    "Tibor 'Rocketman' Nagy",
                    "One Who Obeys Precepts",
                    "The Retainer Of Ergo",
                    "Outzone Supplier",
                    "Hollow Island Weed",
                    "Sheila Marlene",
                    "Unicorn Advance Sentry",
                    "Unicorn Technician",
                    "Basic Tools Merchant",
                    "Container Supplier",
                    "Basic Quality Pharmacist",
                    "Basic Quality Armorer",
                    "Basic Quality Weaponsdealer",
                    "Tailor",
                    "Unicorn Commander Rufus",
                    "Ergo, Inferno Guardian of Shadows",
                    "Unicorn Trooper",
                    "Unicorn Squadleader",
                    "Rookie Alien Hunter",
                    "Unicorn Service Tower Alpha",
                    "Unicorn Service Tower Delta",
                    "Unicorn Service Tower Gamma",
                    "North Alien Signal Tower",
                    "Sean Powell",
                    "Unicorn Guard",
                    "Essence Fragment",
                    "Scalding Flames",
                    "Guide",
                    "Searing Flame",
                    "Searing Flames",
                    "Guard",
                    "Awakened Xan",
                    "Fourth Watch Down",
                    "Mortar Bombardment",
                    "Dogmatic Pestilence",
                    "Flame of the Immortal One",
                    "Calan-Cur",
                    "Pulsating Ice Obelisk",
                    "Unnatural Ice",
                    "Hacked Mechdog",
                    "Harbinger of Pestilence",
                    "Pandemonium Idol",
                    "Laser Drone",
                    "Heatbeam",
                    "Thermal Detonator",
                    "Automated Defense System",
                    "Scalding Flame",
                    "Ju-Ju Doll",
                    "Temporal Vortex",
                    "Gateway to the Past",
                    "Gateway to the Present",
                    "Gateway to the Future",
                    "Masked Eleet",
                    "Dust Brigade Security Drone",
                    "Nanovoider",
                    "Punishment",
                    "Flaming Chaos",
                    "Flaming Punishment",
                    "ICC Peacekeeper",
                    "ICC Peacekeeper Commander",
                    "Vanguard Commander",
                    "Vanguard Watcher",
                    "Male Watcher",
                    "Urban Defense Patroller",
                    "Unicorn Security Administrator",
                    "Alien Heavy Patroller",
                    "Vergil Doppelganger",
                    "Alien Seeker",
                    "Harbingers of Pestilence",
                    "Flaming Vengeance",
                    "Unstable Rift",
                    "Otacustes",
<<<<<<< HEAD
                    "Curse Rot"
=======
                    "Curse Rot",
                    "John McLane"
>>>>>>> aab7ee3ccaa03c6ad6b10dee74da529f4148bb84
        };
    }
}
